services:
  discordbot:
    build:
      context: ./DiscordBot
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    networks:
      - discordbot_network
networks:
  discordbot_network:
    driver: bridge