services:
  discordbot:
    ports:
      - 8080:5129
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile
    environment:
      - Discord:Token=${DISCORD_TOKEN}
      - Discord:ClientId=${DISCORD_CLIENTID}
      - Discord:RedirectUrl=${DISCORD_REDIRECTURI}
      - Discord:ClientSecret=${DISCORD_CLIENTSECRET}
      - Discord:Scopes=${DISCORD_SCOPES}
      - Danbooru:Username=${DANBOORU_USERNAME}
      - Danbooru:Token=${DANBOORU_TOKEN}
