services:
  discordbot:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile
    environment:
      - DiscordBot:Token=${DISCORD_TOKEN}
      - Danbooru:Token=${DANBOORU_TOKEN}
